/* Reuse the exact seven symbol bitmaps and pixel alphabet saved from the approved storyboard. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const dir=path.resolve(__dirname,'..');
const source=process.argv[2]||path.join(dir,'assets/ui-font.json');
const {font,glyphs}=JSON.parse(fs.readFileSync(source,'utf8'));
const fontBits=[],glyphBits=[],tiles=[];
for(let code=32;code<96;code++){
 const rows=font[String.fromCharCode(code)]||[];
 for(let y=0;y<8;y++){const r=rows[y]||'';let byte=0;const off=1+Math.floor((5-r.length)/2);for(let x=0;x<r.length;x++)if(r[x]==='1')byte|=128>>(x+off);fontBits.push(byte)}
}
for(const l of ['O','P','E','N','M','H','I'])for(let y=0;y<8;y++)glyphBits.push(y<7?parseInt(glyphs[l][y]+'0',2):0);
for(let inv=0;inv<2;inv++)for(const b of fontBits){const byte=inv?255^b:b;tiles.push(byte,byte)}
for(const b of glyphBits)tiles.push(b,b);
// Each source bitmap becomes four 8x8 2bpp tiles: TL, TR, BL, BR.
// Duplicate every source pixel in both directions, exactly like load_big.
function enlarge(bits){
 const result=[];
 for(let character=0;character<bits.length/8;character++)
  for(let ty=0;ty<2;ty++)for(let tx=0;tx<2;tx++)for(let y=0;y<8;y++){
   const source=bits[character*8+((ty*8+y)>>1)];let byte=0;
   for(let x=0;x<8;x++)if(source&(128>>((tx*8+x)>>1)))byte|=128>>x;
   result.push(byte,byte);
  }
 return result;
}
const bigFontTiles=enlarge(fontBits),bigGlyphTiles=enlarge(glyphBits);
assert.equal(bigFontTiles.length,4096);
assert.equal(bigGlyphTiles.length,448);
const sprite=[
'0000000000000000','0000003333000000','0000033333300000','0000332222330000',
'0003322222233000','0003323322233000','0003332222333000','0033333333333300',
'0223333333333220','2222333333332222','0222333333332220','0000331111330000',
'0000311001130000','0000011001100000','0000000000000000','0000000000000000'];
const spriteTiles=[];
for(let ty=0;ty<2;ty++)for(let tx=0;tx<2;tx++)for(let y=0;y<8;y++){let lo=0,hi=0;for(let x=0;x<8;x++){const n=+sprite[ty*8+y][tx*8+x];lo|=(n&1)<<(7-x);hi|=((n>>1)&1)<<(7-x)}spriteTiles.push(lo,hi)}
while(spriteTiles.length<128)spriteTiles.push(0);
function arr(type,name,values){return 'const '+type+' '+name+'['+values.length+']={\n'+Array.from({length:Math.ceil(values.length/16)},(_,i)=>' '+values.slice(i*16,i*16+16).map(n=>'0x'+n.toString(16).padStart(type==='uint8_t'?2:4,'0')).join(',')).join(',\n')+'\n};\n'}
fs.mkdirSync(path.join(dir,'generated'),{recursive:true});
fs.writeFileSync(path.join(dir,'generated/ui.c'),'/* Generated by tools/make-ui.cjs. */\n#include <stdint.h>\n'+arr('uint8_t','font_bits',fontBits)+arr('uint8_t','glyph_bits',glyphBits)+arr('uint8_t','ui_tiles',tiles)+arr('uint8_t','sprite_tiles',spriteTiles)+arr('uint8_t','big_font_tiles',bigFontTiles)+arr('uint8_t','big_glyph_tiles',bigGlyphTiles));
console.log('UI: '+tiles.length+' bytes, 135 tiles; seven consistent glyphs. Precomputed large tiles: '+bigFontTiles.length+' font bytes + '+bigGlyphTiles.length+' glyph bytes.');
