/* Native 5x7 UI font, original cipher symbols, and rounded 8x8 panel tiles. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const dir=path.resolve(__dirname,'..');
const source=process.argv[2]||path.join(dir,'assets/ui-font.json');
const {font,glyphs,uiTiles}=JSON.parse(fs.readFileSync(source,'utf8'));
for(const [letter,rows] of Object.entries(font)){
 assert.equal(rows.length,7,'Font height: '+letter);
 assert(rows.every(row=>/^[01]{5}$/.test(row)),'Font width/bits: '+letter);
}
for(const symbol of ['O','P','E','N','M','H','I']){
 assert.equal(glyphs[symbol].length,7,'Symbol height: '+symbol);
 assert(glyphs[symbol].every(row=>/^[01]{7}$/.test(row)),'Symbol width/bits: '+symbol);
}
const fontBits=[],glyphBits=[],tiles=[];
for(let code=32;code<96;code++){
 const rows=font[String.fromCharCode(code)]||[];
 for(let y=0;y<8;y++){const r=rows[y]||'';let byte=0;const off=1+Math.floor((5-r.length)/2);for(let x=0;x<r.length;x++)if(r[x]==='1')byte|=128>>(x+off);fontBits.push(byte)}
}
for(const l of ['O','P','E','N','M','H','I'])for(let y=0;y<8;y++)glyphBits.push(y<7?parseInt(glyphs[l][y]+'0',2):0);
for(let inv=0;inv<2;inv++)for(const b of fontBits){const byte=inv?255^b:b;tiles.push(byte,byte)}
for(const b of glyphBits)tiles.push(b,b);
// Fixed small-tile contract: ASCII 0..63, inverse 64..127, symbols 128..134.
// Panel TL/TR/BL/BR 135..138, top/bottom/left/right 139..142, error 143.
const panelNames=['panelTopLeft','panelTopRight','panelBottomLeft','panelBottomRight','panelTop','panelBottom','panelLeft','panelRight','error'];
for(const name of panelNames){
 const rows=uiTiles[name];
 assert.equal(rows.length,8,'UI tile height: '+name);
 assert(rows.every(row=>/^[01]{8}$/.test(row)),'UI tile width/bits: '+name);
 for(const row of rows){const byte=parseInt(row,2);tiles.push(byte,byte);}
}
assert.equal(tiles.length,2304);
// Each source bitmap becomes four 8x8 2bpp tiles: TL, TR, BL, BR.
// Duplicate every source pixel in both directions, exactly like load_big.
function enlarge(bits){
 const result=[];
 for(let character=0;character<bits.length/8;character++)
  for(let ty=0;ty<2;ty++)for(let tx=0;tx<2;tx++)for(let y=0;y<8;y++){
   const source=bits[character*8+((ty*8+y)>>1)];let byte=0;
   for(let x=0;x<8;x++)if(source&(128>>((tx*8+x)>>1)))byte|=128>>x;
   result.push(byte,byte);
  }
 return result;
}
const bigFontTiles=enlarge(fontBits),bigGlyphTiles=enlarge(glyphBits);
assert.equal(bigFontTiles.length,4096);
assert.equal(bigGlyphTiles.length,448);
const sprite=[
'0000000000000000','0000003333000000','0000033333300000','0000332222330000',
'0003322222233000','0003323322233000','0003332222333000','0033333333333300',
'0223333333333220','2222333333332222','0222333333332220','0000331111330000',
'0000311001130000','0000011001100000','0000000000000000','0000000000000000'];
const spriteTiles=[];
for(let ty=0;ty<2;ty++)for(let tx=0;tx<2;tx++)for(let y=0;y<8;y++){let lo=0,hi=0;for(let x=0;x<8;x++){const n=+sprite[ty*8+y][tx*8+x];lo|=(n&1)<<(7-x);hi|=((n>>1)&1)<<(7-x)}spriteTiles.push(lo,hi)}
while(spriteTiles.length<128)spriteTiles.push(0);
function arr(type,name,values){return 'const '+type+' '+name+'['+values.length+']={\n'+Array.from({length:Math.ceil(values.length/16)},(_,i)=>' '+values.slice(i*16,i*16+16).map(n=>'0x'+n.toString(16).padStart(type==='uint8_t'?2:4,'0')).join(',')).join(',\n')+'\n};\n'}
fs.mkdirSync(path.join(dir,'generated'),{recursive:true});
fs.writeFileSync(path.join(dir,'generated/ui.c'),'/* Generated by tools/make-ui.cjs. */\n#include <stdint.h>\n'+arr('uint8_t','font_bits',fontBits)+arr('uint8_t','glyph_bits',glyphBits)+arr('uint8_t','ui_tiles',tiles)+arr('uint8_t','sprite_tiles',spriteTiles)+arr('uint8_t','big_font_tiles',bigFontTiles)+arr('uint8_t','big_glyph_tiles',bigGlyphTiles));
console.log('UI: '+tiles.length+' bytes, 144 tiles; seven unchanged cipher symbols and nine panel/error tiles. Precomputed large tiles: '+bigFontTiles.length+' font bytes + '+bigGlyphTiles.length+' glyph bytes.');
